"""added diasbled to client

Revision ID: 541528e8e59c
Revises: a0c152cd1b97
Create Date: 2024-06-14 19:38:51.094674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541528e8e59c'
down_revision: Union[str, None] = 'a0c152cd1b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('disabled', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'disabled')
    # ### end Alembic commands ###
