"""adding inbound detail

Revision ID: 6612d313bd94
Revises: 96c2477801ea
Create Date: 2024-05-19 12:14:37.435619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6612d313bd94'
down_revision: Union[str, None] = '96c2477801ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('detail', sa.String(), server_default=' ', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbounds', 'detail')
    # ### end Alembic commands ###
