"""create client usage model

Revision ID: 7893b5430c3e
Revises: 59fb151c4219
Create Date: 2024-06-24 18:24:41.042075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7893b5430c3e"
down_revision: Union[str, None] = "59fb151c4219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("usage", sa.Float(), nullable=False),
        sa.Column("last_usage", sa.Float(), nullable=False),
        sa.Column("client", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clients_usage")
    # ### end Alembic commands ###
