"""adding relationship for client in clientusage

Revision ID: 830fe04b59f9
Revises: 7893b5430c3e
Create Date: 2024-06-25 19:36:28.581458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "830fe04b59f9"
down_revision: Union[str, None] = "7893b5430c3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients_usage", sa.Column("client_id", sa.Integer(), nullable=False))
    op.drop_constraint("clients_usage_client_fkey", "clients_usage", type_="foreignkey")
    op.create_foreign_key(
        None, "clients_usage", "clients", ["client_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("clients_usage", "client")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients_usage",
        sa.Column("client", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "clients_usage", type_="foreignkey")
    op.create_foreign_key(
        "clients_usage_client_fkey",
        "clients_usage",
        "clients",
        ["client"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("clients_usage", "client_id")
    # ### end Alembic commands ###
