"""adding inbounds

Revision ID: 96c2477801ea
Revises: ff9c9cbe1da3
Create Date: 2024-05-19 00:51:09.064032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "96c2477801ea"
down_revision: Union[str, None] = "ff9c9cbe1da3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("host", sqlalchemy_utils.types.url.URLType(), nullable=False),
        sa.Column("inbound_id", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "users",
        "tgid",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=9),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "tgid",
        existing_type=sa.String(length=9),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.drop_table("inbounds")
    # ### end Alembic commands ###
