"""adding email to clients

Revision ID: a0c152cd1b97
Revises: 4a427e926d13
Create Date: 2024-06-14 13:23:56.178510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0c152cd1b97"
down_revision: Union[str, None] = "4a427e926d13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("email", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "email")
    # ### end Alembic commands ###
