"""updating inbound model

Revision ID: b58108415755
Revises: bbe16ac2f7d7
Create Date: 2024-05-20 17:54:52.397011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58108415755'
down_revision: Union[str, None] = 'bbe16ac2f7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('base_link', sa.String(), nullable=False))
    op.create_unique_constraint('_host_location_uc', 'inbounds', ['host', 'inbound_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_host_location_uc', 'inbounds', type_='unique')
    op.drop_column('inbounds', 'base_link')
    # ### end Alembic commands ###
