"""new remark column and new password column

Revision ID: d7c691995e95
Revises: 4563e770cb7c
Create Date: 2024-05-22 09:11:52.670437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7c691995e95"
down_revision: Union[str, None] = "4563e770cb7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("password", sa.String(), nullable=True))
    op.alter_column(
        "clients",
        "uuid",
        existing_type=sa.UUID(),
        nullable=True,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.add_column("inbounds", sa.Column("remark", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbounds", "remark")
    op.alter_column(
        "clients",
        "uuid",
        existing_type=sa.UUID(),
        nullable=False,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.drop_column("clients", "password")
    # ### end Alembic commands ###
